services:
  kicad_service:
    build:
      context: .
      dockerfile: Dockerfile # The path to our Dockerfile
    network_mode: host
    environment:
      - DISPLAY=${DISPLAY} # Connecting host and container GUI
    command: kicad
    tty: true
    privileged: true
    volumes:
      - ../:/workspace:cached # Workspace folder
      - /tmp/.X11-unix:/tmp/.X11-unix # Connecting host and container GUI
      # WORK-IN-PROGRESS
      #- ../data/shared-kicad/:/usr/share/kicad # KiCad Environment Variables Path(s)
      #- ../data/local-shared-kicad/:/root/.local/share/kicad/ # KiCad Environment Variables Path(s)
      #- ../data/config-kicad/:/root/.config/kicad/ # KiCad Path to Config

